apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: develop
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=nginx:stable-alpine
    argocd-image-updater.argoproj.io/nginx.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: develop
    argocd-image-updater.argoproj.io/nginx.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/nginx.helm.image-tag: image.tag
spec:
  destination:
    namespace: develop
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    path: example-app
    repoURL: https://github.com/jblorincz/argocd-image-updater-example
    targetRevision: develop
