apiVersion: argoproj.io/v1alpha1
kind: Application
# The production environment is not going to be using the updater
# So the app can be kept vanilla.
metadata:
  name: production
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: production
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    path: example-app
    repoURL: https://github.com/jblorincz/argocd-image-updater-example
    targetRevision: master
